Product.create(name: "Almond Toe Court Shoes, Patent Black", category: "Women's footwear", price: 9900, stock_quantity: 5)
Product.create(name: "Suede Shoes, Blue", category: "Women's footwear", price: 4200, stock_quantity: 4)
Product.create(name: "Leather Driver Saddle Loafers, Tan", category: "Men's footwear", price: 3400, stock_quantity: 12)
Product.create(name: "Flip Flops, Red", category: "Men's footwear", price: 1900, stock_quantity: 6)
Product.create(name: "Flip Flops, Blue", category: "Men's footwear", price: 1900, stock_quantity: 0)
Product.create(name: "Gold Button Cardigan, Black", category: "Women's casualwear", price: 16700, stock_quantity: 6)
Product.create(name: "Cotton Shorts, Medium Red", category: "Women's casualwear", price: 3000, stock_quantity: 5)
Product.create(name: "Fine Stripe Short Sleeve Shirt, Grey", category: "Men's casualwear", price: 4999, stock_quantity: 9)
Product.create(name: "Fine Stripe Short Sleeve Shirt, Green", category: "Men's casualwear", price: 3999, stock_quantity: 3)
Product.create(name: "Sharkskin Waistcoat, Charcoal", category: "Men's formalwear", price: 7500, stock_quantity: 2)
Product.create(name: "Lightweight Patch Pocket Blazer, Deer", category: "Men's footwear", price: 17550, stock_quantity: 1)
Product.create(name: "Bird Print Dress, Black", category: "Women's formalwear", price: 27000, stock_quantity: 10)
Product.create(name: "Mid Twist Cut-Out Dress, Pink", category: "Women's formalwear", price: 54000, stock_quantity: 5)
